// TODO: reemplazar stub con pdfkit, puppeteer o @react-pdf/renderer
class TicketPdfService {
  constructor() {
    console.info('[TicketPdfService] Initialized (stub mode).');
  }

  async generateTicketPdf({ ticket, comments = [], productName = 'N/A' }) {
    console.info(`[TicketPdfService] generateTicketPdf called for ticket: ${ticket.ticketId}`);

    await new Promise((resolve) => setTimeout(resolve, 10));

    const content = [
      `TICKET REPORT (STUB)`,
      `===================`,
      `ID:          ${ticket.ticketId}`,
      `Subject:     ${ticket.subject}`,
      `Status:      ${ticket.status}`,
      `Level:       L${ticket.currentLevel}`,
      `Type:        ${ticket.type}`,
      `Impact:      ${ticket.impact}`,
      `Product:     ${productName}`,
      `Created:     ${ticket.createdAt}`,
      ``,
      `Description:`,
      ticket.description,
      ``,
      `Comments (${comments.length}):`,
      ...comments.map(
        (c, i) =>
          `  [${i + 1}] ${c.authorName} (${c.authorRole}) @ ${c.createdAt}: ${c.content}`
      ),
      ``,
      `-- Generated by Micro-Soporte L1/L2 (stub) --`,
    ].join('\n');

    return Buffer.from(content, 'utf-8');
  }

  async generateTicketListPdf({ tickets = [], title = 'Ticket Report' }) {
    console.info(`[TicketPdfService] generateTicketListPdf called. Count: ${tickets.length}`);

    await new Promise((resolve) => setTimeout(resolve, 10));

    const content = [
      title,
      '='.repeat(title.length),
      `Total tickets: ${tickets.length}`,
      `Generated at:  ${new Date().toISOString()}`,
      ``,
      ...tickets.map(
        (t, i) =>
          `[${i + 1}] ${t.ticketId} | ${t.subject} | ${t.status} | L${t.currentLevel}`
      ),
      ``,
      `-- Generated by Micro-Soporte L1/L2 (stub) --`,
    ].join('\n');

    return Buffer.from(content, 'utf-8');
  }
}

module.exports = { TicketPdfService };
